#!/usr/bin/env python3
"""Fail the build if a plug-in the banks reference isn't wired into the app.

PluginInfo.json is regenerated by Wwise every time SoundBanks are built, so it
is ground truth for which plug-ins the banks actually use. wwise_audio.cpp and
CMakeLists.txt are hand-maintained lists of the matching #include and .a link
line for each one -- the two lists that this bug (see mirror_app history: the
Parametric EQ landed in a bank and stayed unregistered for weeks, playing
silently in Authoring and doing nothing in the app) keeps falling out of sync
with. This script is the thing that used to be "remembering to check the
diff by hand."

A plug-in with a StaticLib entry needs:
  - "#include <.../<StaticLib>Factory.h>"   (anywhere) in wwise_audio.cpp
  - "lib<StaticLib>.a"                       (anywhere) in CMakeLists.txt

AudioDevice entries (System, No Output) have no StaticLib and are skipped.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGIN_INFO = ROOT.parent / "WwiseProject" / "GeneratedSoundBanks" / "Mac" / "PluginInfo.json"
WWISE_AUDIO_CPP = ROOT / "src" / "wwise_audio.cpp"
CMAKELISTS = ROOT / "CMakeLists.txt"


def main() -> int:
    if not PLUGIN_INFO.exists():
        print(f"check_wwise_plugins: {PLUGIN_INFO} not found -- generate "
              "SoundBanks in Wwise at least once before building", file=sys.stderr)
        return 1

    info = json.loads(PLUGIN_INFO.read_text())
    cpp_text = WWISE_AUDIO_CPP.read_text()
    cmake_text = CMAKELISTS.read_text()

    missing = []
    for lib in info["PluginInfo"]["PluginLibs"]:
        static_lib = lib.get("StaticLib")
        if not static_lib:
            continue  # AudioDevice entries carry no static lib to link.
        needs_include = f"{static_lib}Factory.h"
        needs_link = f"lib{static_lib}.a"
        problems = []
        if needs_include not in cpp_text:
            problems.append(f"missing #include .../{needs_include} in {WWISE_AUDIO_CPP.name}")
        if needs_link not in cmake_text:
            problems.append(f"missing {needs_link} in {CMAKELISTS.name} link libraries")
        if problems:
            missing.append((lib["LibName"], lib["LibId"], problems))

    if not missing:
        return 0

    print("check_wwise_plugins: bank references plug-ins the app never registers:",
          file=sys.stderr)
    for name, lib_id, problems in missing:
        print(f"  {name} (LibId {lib_id})", file=sys.stderr)
        for p in problems:
            print(f"    - {p}", file=sys.stderr)
    print("These load without error and process nothing -- silent in the app, "
          "fine in Authoring.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
